name: testes

on:
  push:
  pull_request:

jobs:
  windows:
    name: Windows, PowerShell 5.1 e 7
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Guarda (Windows PowerShell 5.1)
        shell: powershell
        run: ./testes/testar-guarda.ps1
      - name: Guarda (PowerShell 7)
        shell: pwsh
        run: ./testes/testar-guarda.ps1
      - name: Instalador (Windows PowerShell 5.1)
        shell: powershell
        run: ./testes/testar-instalador.ps1
      - name: Instalador (PowerShell 7)
        shell: pwsh
        run: ./testes/testar-instalador.ps1
